name: Deploy Hollow-Depths
run-name: ${{ github.actor }} is Deploying Hollow-Depths
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    env: 
      BASE_PATH: "/Hollow-Depths/"
      DATABASE_URL: "postgresql://gasexwzu:gawqxseabmrhyiknabil@alpha.europe.mkdb.sh:5432/hcuwjytm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v3
        with:
          runtime: node@24
          version: 12
          cache: True
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      - run: pnpm install
      
      - name: Build
        run: PORT=8080 pnpm build
        
      - name: Upload metroidvania
        uses: actions/upload-pages-artifact@v4
        with:
          name: metroidvania
          path: |
            artifacts/metroidvania/dist/public/
          if-no-file-found: error

      - name: Upload Api-server
        uses: actions/upload-pages-artifact@v4
        with:
          name: api-server
          path: |
            artifacts/api-server/dist/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
            artifact_name: metroidvania
      - name: deploy api
        id: deployment-api
        uses: actions/deploy-pages@v5
        with:
          artifact_name: api-server
